spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQC8FG3OXA9bD0YJOQdOCqocYB6JdBXbrQMOVa5Sw9eTSsXceegfBE1BDkCO9AmGg6rg86NCVXHCImeokzE3p0GQtshTAlhihaNNmBJpEaSdP4u1Z/hvHt2VOhi/1OBFsG7+Nfyaj9JqmtwdLDgi6qophMwdJ23YGFM0pacUiw3qcET61yg2B07/RR42d09/cZ34vrn2mojqeqOdumOJF7tzjpeV4XpEV+r4A1WJ0xS0yuyceyQsERnC8hqlMI6zI+1LJIaWlETdokjS0Oq5EYVSAEHpk6VZxraMC2d3F8FaXsjdudMv2ewQomCpNRWRQht05l8lLRTuunzaGLdtuzClzGnHmLkObjW7UYlqwccmHlfdO8UYp484XEPus8HFq84='

token:
  expiration_time: 864000000
  secret: '{cipher}AQBja2Ktbe39Bb4zzquf6EJX2qc8oj8/etQf7+u/E2xPS02/cezCussCEA5O6ynxr6+K0FHzC2oYtXBI5E7mJo9On5GS06ZHmURL8Q9RcA2BtDaat0osQC4Jv5+dX0LgUV91s6qA9RConk2kQoSEsbQWr5MptG/eqFaxjYQ76b2dfaT7ZiQQGIoJnoeGoJNknA+zZZxrrrtCDaXXowtm08LsoQAva1G/lTHM3OQ84hqJTXL6g6gySHVtMOCWqjMQAMOu5q9PCOCFdJVQM0Ir8TpKColUPrqWZVQIIk10dfSopBvdHLGlu9GSm+sWKd0Ay/t7ybeKn7dnGZ/3IIPvQixUkG73lsA4+xJIjHfBtGgGUHiyfMQrY1LJs12WDZcQ9wFhHnXe2jCsb0LEFIjW+xtT'

gateway:
  ip: localhost
